"""
Index Builder - Creates Sentence embedding for captions and builder a FAISS Index

This script:
1. loads captions from a json file (generated by the caption_generator.py)
2. Embeds captions using SentenceTranformers
3. Creates a Faiss index for fast similarity search
4. Saves the index and associated metadata

Usage:
    python -m src.index_builder --captions_file data/captions.json -- output_dir data/

"""

import os
import json
import argparse
import numpy as np
from tqdm import tqdm
import faiss
from sentence_transformers import SentenceTransformer

def load_captions(captions_file):
    """
    args:
        captions_file: Path to the json file with captions

    Returns:
        List of dictionaries with image data

    """
    print(f"Loading captions fron {captions_file}")
    with open(captions_file,'r') as f:
        captions_data = json.load(f)
    print(f"loaded{len(captions_data)} caption entries")
    return captions_data

def create_embedding(captions_data, model_name ="sentence-transformers/all-MiniLM-L6-v2"):
    """
    Create embedding for all captions using SentencesTransformers.

    Args:
        captions_data: List of dictionaries with caption information
        model name = name of the sentencetransformer model to use 

    Returns :
        Tuple of (embedding array, list of image path, list of captions)

    """

    print(f"Loading embedding model{model_name}")
    model = SentenceTransformer(model_name)

    #extract captions and image path 
    captions =[item['caption'] for item in captions_data]
    image_path = [item['image_path']for item in captions_data]

    # generate embeddings
    print("Generating embedding for all captions ....")
    embeddings = model.encode(captions, show_progress_bar=True, convert_to_numpy=True)
    print(f"Created embedding with shape: {embeddings.shape}")
    return embeddings, image_path, captions

def build_faiss_index(embeddings, output_dir):
    """
    Build and save a Faiss index for the embeddings
    
    args:
        embeddings : Numpy array of embeddings
        output_dir : Directory to save the index

    Returns:
        Path to the saved index

    """
    # Determine embedding dimension
    dimension = embeddings.shape[1]

    # create a faiss index using L2 distance (euclidean)
    # Normalize embedding before creating index
    faiss.normalize_L2(embeddings)
    index = faiss.IndexFlatIP(dimension) # Inner product similarity (for normalized vectors = cosine similarity)

    # Add embedding to the index
    index.add(embeddings.astype(np.float32))

    # Save the Index
    index_path = os.path.join(output_dir, "captions.index")
    faiss.write_index(index, index_path)

    print(f"Faiss Index created with {index.ntotal} vectirs ")
    print(f"saved index to {index_path}")

    return index_path

def save_metadata(image_paths, captions, output_dir):
    """
    Save metadata (image paths and captions) to JSON files.
    
    Args:
        image_paths: List of image paths
        captions: List of captions
        output_dir: Directory to save the metadata
    """
    # Save image paths (order matters - must match index order)
    image_paths_file = os.path.join(output_dir, "image_paths.json")
    with open(image_paths_file, 'w') as f:
        json.dump(image_paths, f, indent=2)
    
    # Save captions separately for convenience
    captions_file = os.path.join(output_dir, "processed_captions.json")
    captions_data = [{"image_path": path, "caption": caption} 
                     for path, caption in zip(image_paths, captions)]
    with open(captions_file, 'w') as f:
        json.dump(captions_data, f, indent=2)
    
    print(f"Saved {len(image_paths)} image paths to {image_paths_file}")
    print(f"Saved processed captions to {captions_file}")

def main():
    # Parse command line arguments
    parser = argparse.ArgumentParser(description='Create embeddings and FAISS index for fashion captions')
    parser.add_argument('--captions_file', type=str, required=True, 
                        help='Path to JSON file containing captions')
    parser.add_argument('--output_dir', type=str, default='data', 
                        help='Directory to save the index and metadata')
    parser.add_argument('--model_name', type=str, 
                        default='sentence-transformers/all-MiniLM-L6-v2',
                        help='SentenceTransformer model to use for embeddings')
    
    args = parser.parse_args()
    
    # Ensure output directory exists
    os.makedirs(args.output_dir, exist_ok=True)
    
    # Load captions data
    captions_data = load_captions(args.captions_file)
    
    # Create embeddings
    embeddings, image_paths, captions = create_embedding(captions_data, args.model_name)
    
    # Build and save FAISS index
    index_path = build_faiss_index(embeddings, args.output_dir)
    
    # Save metadata
    save_metadata(image_paths, captions, args.output_dir)
    
    print("Index building completed successfully!")

if __name__ == "__main__":
    main()

